name: Android CI

on:
  push:
    branches: [ "master2" ]
  pull_request:
    branches: [ "master2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build app
        run: ./gradlew assemble
# auth for gradelw command in git
# git update-index --chmod=+x ./gradlew




